<h3><?php echo $titulo; ?></h3>

<?php if(count($messages)):?>
    <?php foreach($messages as $value):
        $key = key($value);
        $message = current($value);
    ?>
<div class="alert alert-<?php echo $key?>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?php echo $message; ?>
    </div>
    <?php endforeach;?>
<?php endif;?>

<div class="well">
    <table class="table">
        <thead>
            <tr>
                <td>Nome:</td>
                <td>Cnpj:</td>
                <td>Endereço:</td>
                <td>Telefone:</td>
                <td>Telefone Opcional</td>
                <td>Email</td>
                <td>Opções</td>
            </tr>
        </thead> 
        <tbody>
            <?php if(count($fornecedores)):
     foreach($fornecedores as $forn):?>
            <tr>
                <td><?php echo $forn->nome?></td>
                <td><?php echo $forn->cnpj?></td>
                <td><?php echo $forn->endereco?></td>
                <td><?php echo $forn->telefone1?></td>
                <td><?php echo $forn->telefone2?></td>
                <td><?php echo $forn->email?></td>
                <td>
                    <a href="/fornecedor/editar/<?php echo $forn->id;?>"><i class="icon-pencil"></i>
                    <a href="/fornecedor/remover/<?php echo $forn->id;?>"><i class="icon-remove-sign"></i>
                </td>
            </tr>
            
            <?php endforeach; 
            else: ?>
            <tr>
                <td colspan="4">Não há fornecedor Cadastrado!</td>
            </tr>
            <?php endif; ?>        
        </tbody>
    </table>
    <?php echo $this->paginationControl($fornecedores, 'Sliding', 'clinica/partials/paginator/control.phtml')?>
</div>
