
<div class="topo-table">
 
    <div class="input-append pull-right">
        <form>
            <input class="span2" placeholder="Localizar" id="appendedInputButtons" type="text">
            <button class="btn" type="button">Telefone</button>
            <button class="btn" type="button">Nome</button>
        </form>
    </div>
</div>

<br />
 
<div class="corpo-table">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Tel. Principal</th>
                <th>Qua.</th>
                <th>Data Criação</th>  
                <th>Ação</th>  
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 1; $i <= 5; $i++): ?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td>Fortaleza Ceará Brasil</td>
                    <td>(085)85858585</td>
                    <td>2</td>
                    <td>29/01/2013</td>
                    <td>
                        <a class="btn btn-mini btn-info" href="">Visualizar</a>
                        <a class="btn btn-mini btn-warning" href="">Editar</a>
                        <a class="btn btn-mini btn-danger" href="">Apagar</a>
                    </td>
                </tr>
            <?php endfor; ?>
        </tbody>
    </table>
 
    <div class="pagination">
        <ul>
            <li><a href="#">Anterior</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">Próximo</a></li>
        </ul>
    </div>
</div>
